export const COPY = {
  hero: {
    title: 'No More Gaps',
    line1: 'You don’t choose a 3-hour gap on purpose.',
    line2: 'You just get tired of trying every course combination.',
    resolution: 'Gadwal doesn’t get tired. It finds the best schedule for you.',
    primary: 'Find my best schedule',
    guide: 'Learn how',
    legacyTitle: 'Stop wasting hours between courses.',
    question: 'Have you ever had a course at 10 AM and your next one was at 1 PM?',
    problem: 'That’s 3 hours stuck on campus, waiting around for your next course.',
    empathy: 'Nobody wants to spend their day like that.',
    why: 'Gadwal finds you a schedule that actually makes sense.',
    legacyPrimary: 'Find my best schedule',
  },
  how: {
    title: 'How Gadwal works',
    intro: 'You choose the courses you want.',
    sections: 'Each course can have multiple sections with different days and times.',
    combinations: 'That means there can be hundreds or even thousands of possible combinations.',
    manual: 'You could try to test them yourself...',
    handoff: 'Or let Gadwal do it for you.',
    searches: 'Gadwal checks all valid combinations and shows up to three valid options for each number of class days.',
    campusGrouping: 'grouped by class-day count',
    fewerDays: 'different class-day counts',
    lessGap: 'clear schedule options',
    noConflicts: 'no course conflicts',
    chooseBest: 'Then you compare the valid options and choose the schedule that works best for you.',
    startAction: 'Start adding courses',
  },
  promise: {
    title: 'Our Promise',
    core: 'Gadwal works with the real options your university gives you.',
    available: 'You choose the courses you want, and Gadwal checks the options available for them.',
    cannot: "Gadwal can’t create new options, change meeting times, or add courses that aren’t available.",
    startAction: 'Start adding courses',
    exampleHeading: 'For example',
    exampleIntro: 'Say you want 4 courses with the credits you need and a required course.',
    exampleSpread: 'The available course options might only fit together across specific days and times.',
    exampleImpossible: 'Gadwal cannot force an option if it conflicts with your required course.',
    exampleTruth: 'That real option data determines which valid schedules can be built.',
    capabilityHeading: 'Here’s what Gadwal can do',
    capabilityIntro: 'Choosing options manually can leave you with long gaps between courses.',
    gapChange: 'Within each class-day group, Gadwal shows up to three valid schedule options so you can compare them yourself.',
    sectionsExist: 'That improvement only happens when the required options and valid combinations actually exist.',
    impossibleHeading: 'What if the perfect schedule isn’t possible?',
    okay: 'That’s okay.',
    bestAvailable: 'Gadwal works with the options that actually exist and finds the best valid schedules available.',
    maybeNoImprovement: 'Some class-day counts may have fewer valid options than others.',
    depends: 'Everything depends on the options your university offers.',
    screenshotsHeading: 'Your screenshots matter',
    screenshotSource: 'Gadwal can only use the information you give it.',
    screenshotMissing: 'If an option isn’t in your screenshots, Gadwal can’t consider it.',
    screenshotFresh: 'Make sure your screenshots are clear and up to date.',
    screenshotUpdate: 'If your university changes an option, day, or time later, update your screenshots so Gadwal has the latest information.',
    finalHeading: 'One last thing',
    finalNoRegister: 'Gadwal doesn’t register you or make changes in your university portal.',
    finalSearchOnly: 'It only searches and compares the options you provide.',
    finalTruth: 'Your university portal is the final source of truth.',
    finalYouChoose: 'You choose the courses and the final schedule.',
    finalSearch: 'Gadwal checks valid option combinations and shows the valid schedules it found.',
    finalDecision: 'You make the final decision.',
    finalTrust: 'We’ll show you what’s actually possible from the options you provide. We won’t invent a better schedule just to make the result look better.',
  },
  trust: {
    aiNotice: 'Using screenshots? We read the course names, options, days, and times for you. The image is sent to Gadwal for that step. Check what we found before building.',
    privacyLink: 'How your data is handled',
    review: 'Check the course names, options, days, times, and credits before building.',
  },
  flow: {
    screenshotTab: 'Use screenshots',
    screenshotHelp: 'Best for a quick setup.',
    manualTab: 'Enter courses',
    manualHelp: 'Add a course yourself when a screenshot does not have it.',
  },
  completeness: {
    exhaustive: 'We checked the full search that fit within the search limits.',
    sampled: 'We checked a smaller group of course combinations. Other valid schedules may exist.',
    capped: 'The search hit a work limit before every combination could be checked. Other valid schedules may exist.',
    cancelled: 'The search was canceled before a complete result set was produced.',
  },
  empty: {
    resultsTitle: 'We couldn’t find a schedule that fits these choices.',
    resultsBody: 'Try changing the target number of courses or total credits, review your must-take choices, or check the available course options.',
  },
  methods: {
    screenshotSubtitle: 'Best when you want it fast.',
    manualSubtitle: 'Add a course yourself when a screenshot does not have it.',
  },
  demo: {
    title: 'Screenshot guide',
    subtitle: '',
    howTitle: 'How to take your screenshots',
    chapter1: 'Part 1 · Get ready',
    chapter1Label: 'PART 1 · GET READY',
    chapter1Title: 'Get ready',
    chapter1Purpose: 'Get into the correct place and clear your schedule.',
    step1Title: '1. Open Advising',
    step1Body: 'Go to your student portal and click Advising.',
    step2Title: '2. Clear your schedule',
    step2Body: 'Remove all courses from your schedule.',
    step2Note: 'Start with an empty schedule so you can see all available options.',
    chapter2: 'Part 2 · Capture',
    chapter2Label: 'PART 2 · CAPTURE',
    chapter2Title: 'Capture',
    chapter2Purpose: 'Capture every available option with a clear screenshot.',
    step3Title: '3. Open each course',
    step3Body1: 'Click Add Courses, then select a course to view its available options.',
    step3Body2: 'You may see multiple sections, such as FIN201-New07 or FIN201-New09.',
    step3Rule: 'Only choose courses you’re actually willing to take.',
    step4Title: '4. Take a screenshot',
    step4Body: 'Click each available option and take a screenshot. For example, Nutrition has just one option, NUT10102-MCM, so take one screenshot, click Back, and move on to your next course.',
    step4ChecklistTitle: 'Make sure it shows:',
    step5Title: '5. Repeat for every course',
    step5Body1: 'Take a screenshot of each available option for your courses. For example, if Financial Management has FIN201-New07 and FIN201-New09, take one screenshot of each.',
    step5Body2: 'Return to your course list and repeat for each remaining course.',
    step6Title: '6. Summary',
    step6Body: 'Review the screenshots you gathered across all your courses.',
    chapter3: 'Part 3 · Finish',
    chapter3Label: 'PART 3 · FINISH',
    chapter3Title: 'Finish',
    step7Title: '7. Upload your screenshots',
    step7Body: 'Once you’ve captured all the options you want, upload your screenshots to Gadwal.',
    step7Ending: 'Upload them when you’re ready. Then choose the number of courses and credits you need, mark any mandatory courses, and let Gadwal search the valid option combinations.',
    step7Next: 'Gadwal removes conflicting schedules, groups valid schedules by number of class days, shows up to three options in each group, and lets you choose the schedule you prefer.',
    tipsTitle: 'Quick tips',
  },
} as const;

export type SearchCompletenessCopy = keyof typeof COPY.completeness;
