import React, { useEffect, useState } from 'react';
import { ModalShell } from './ModalShell';
import { fetchJson } from '../services/resilientFetch';
import { Star, Download, Trash2, Bell, BookOpen, CalendarDays, Shield, CreditCard } from 'lucide-react';
import { formatDate, formatDateTime } from '../utils/dateFormatting';

export interface AccountCenterProps {
  isOpen: boolean;
  onClose: () => void;
  onOpenUpgrade?: () => void;
  onStartNewTerm?: () => void;
  onOpenAuth?: (view: 'forgot') => void;
  onLogout?: () => void;
  onResume?: () => void;
}

export const AccountCenter: React.FC<AccountCenterProps> = ({ isOpen, onClose, onOpenUpgrade, onStartNewTerm, onOpenAuth, onLogout, onResume }) => {
  const [tab,setTab]=useState<'overview'|'courses'|'schedules'|'payments'|'notifications'|'security'|'help'>('overview');
  const [data,setData]=useState<any>(null); const [notifications,setNotifications]=useState<any[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const [currentPassword,setCurrentPassword]=useState(''); const [newPassword,setNewPassword]=useState(''); const [confirmPassword,setConfirmPassword]=useState('');
  const [newEmail,setNewEmail]=useState(''); const [emailPassword,setEmailPassword]=useState('');
  const load=async()=>{try{const {response:res,data:d}=await fetchJson('/api/account/overview',{credentials:'same-origin'});if(!res.ok) throw new Error(d.error||'Could not load account.'); setData(d); const n=await fetchJson('/api/account/notifications',{credentials:'same-origin'}); if(n.response.ok)setNotifications(n.data.notifications||[]);}catch(e:any){setError(e.message||'Could not load account.');}};
  useEffect(()=>{if(isOpen)void load();},[isOpen]);
  if(!isOpen)return null;
  const perform=async(id:string,fn:()=>Promise<void>)=>{try{setBusy(id);setError('');await fn();await load();}catch(e:any){setError(e.message||'Action failed.');}finally{setBusy('');}};
  const deleteAccount=async()=>{const confirmation=window.prompt('Type DELETE GADWAL to schedule deletion of your Gadwal account data in 7 days.');if(confirmation!=='DELETE GADWAL')return;const password=window.prompt('Enter your current password to confirm this sensitive action.');if(!password)return;await perform('delete',async()=>{const r=await fetchJson('/api/account/delete-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation,password})});if(!r.response.ok)throw new Error(r.data.error||'Could not schedule deletion.');});};
  const changePassword=async(e:React.FormEvent)=>{e.preventDefault();if(newPassword!==confirmPassword){setError('The new passwords do not match.');return;}await perform('password',async()=>{const r=await fetchJson('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});if(!r.response.ok)throw new Error(r.data.error||'Could not change your password.');setCurrentPassword('');setNewPassword('');setConfirmPassword('');});};
  const changeEmail=async(e:React.FormEvent)=>{e.preventDefault();await perform('email',async()=>{const r=await fetchJson('/api/auth/change-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({newEmail,emailPassword})});if(!r.response.ok)throw new Error(r.data.error||'Could not start email change.');setNewEmail('');setEmailPassword('');});};
  const active=data?.access?.hasScheduleAccess;
  const feedbackEmail = String(import.meta.env.VITE_FEEDBACK_EMAIL || '').trim();
  const pendingPayment = data?.payments?.find((x:any)=>x.status==='PENDING');
  return <ModalShell isOpen={isOpen} onClose={onClose} title="My Account">
    <div className="flex gap-1 overflow-x-auto border-b border-line mb-5 pb-1">{[['overview','Overview'],['courses','Courses'],['schedules','Schedules'],['payments','Access & payments'],['notifications',`Notifications${data?.unreadCount?` · ${data.unreadCount}`:''}`],['security','Security'],['help','Help']].map(([id,label])=><button key={id} onClick={()=>setTab(id as any)} className={`px-3 py-2 min-h-[44px] whitespace-nowrap text-sm font-semibold rounded-lg ${tab===id?'bg-ink text-white':'text-text-secondary hover:bg-mist'}`}>{label}</button>)}</div>
    {error&&<div className="mb-4 p-3 rounded-lg bg-red-50 text-red-700 text-sm" role="alert">{error}</div>}
    {tab==='overview'&&data&&<div className="space-y-4">
      <div className="p-5 rounded-2xl border border-line bg-mist"><p className="text-xs uppercase tracking-wide text-text-muted">Gadwal access</p><h3 className="text-xl font-black mt-1">{data.access.accessLabel}</h3><p className="text-sm text-text-secondary mt-1">{data.access.daysRemaining!=null?`${data.access.daysRemaining} days remaining · expires ${formatDate(data.access.expiresOn)}`:'No paid access currently'}</p></div>
      {data.profile?.onboardingCompletedAt && ((data.currentCourses&&Array.isArray(data.currentCourses)&&data.currentCourses.length>0)||data.schedules?.length>0) && <div className="p-5 rounded-2xl border border-accent/20 bg-accent/5"><p className="text-xs uppercase tracking-wide text-text-muted">Continue where you left off</p><p className="font-black text-lg mt-1">Your current course work is saved.</p><p className="text-sm text-text-secondary mt-1">Resume your current term instead of starting over.</p><button onClick={()=>onResume?.()} className="mt-4 min-h-[44px] px-4 rounded-lg bg-ink text-white font-semibold">Continue your schedule</button></div>}
      <div className="grid sm:grid-cols-2 gap-3"><div className="p-4 border border-line rounded-xl"><p className="text-xs text-text-muted">Student</p><p className="font-semibold mt-1">{data.profile?.displayName || 'MIU Student'}</p><p className="text-xs text-text-muted mt-1">{data.profile?.email}</p><p className="text-xs text-green-700 mt-1">Verified MIU account</p></div><div className="p-4 border border-line rounded-xl"><p className="text-xs text-text-muted">Current academic period</p><p className="font-semibold mt-1">{data.context.term} · {data.context.academicYear}</p><p className="text-xs text-text-muted mt-1">Free run: {data.access.freeRunStatus==='available'?'Available':data.access.freeRunStatus==='in-progress'?'In progress':'Used'}</p></div></div>
      {data.access.previousAccessExpired&&<div className="p-4 rounded-xl border border-line bg-mist"><p className="font-bold">{data.access.previousAccessLabel}</p><p className="text-sm text-text-secondary mt-1">Your saved courses and schedules are still available in your account.</p></div>}
      {!active&&data.access.freeRunStatus==='used'&&<button onClick={onOpenUpgrade} className="w-full min-h-[46px] rounded-xl bg-accent text-white font-bold">Get Gadwal access</button>}
      {data.profile?.deletionScheduledFor&&<div className="p-4 border border-alert/30 bg-alert/5 rounded-xl"><p className="font-bold">Account deletion scheduled</p><p className="text-sm mt-1">Your data will be deleted on {formatDateTime(data.profile.deletionScheduledFor)}.</p><button className="mt-3 min-h-[44px] px-4 border border-line rounded-lg font-semibold" disabled={busy==='cancel'} onClick={()=>perform('cancel',async()=>{const password=window.prompt('Enter your current password to cancel account deletion.');if(!password)return;const r=await fetchJson('/api/account/delete-cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.response.ok)throw new Error(r.data.error||'Could not cancel.');})}>{busy==='cancel'?'Cancelling…':'Cancel deletion'}</button></div>}
    </div>}
    {tab==='courses'&&data&&<div className="space-y-3"><button onClick={onStartNewTerm} className="min-h-[44px] px-4 rounded-lg bg-ink text-white font-semibold">Start a new term</button>{data.courseSets.length?data.courseSets.map((c:any)=><div key={c.id} className="p-4 border border-line rounded-xl flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><p className="font-bold">{c.title||`${c.term} ${c.academicYear}`}</p><p className="text-sm text-text-secondary">{c.term} · {c.academicYear} · {Array.isArray(c.courseData)?c.courseData.length:0} courses</p></div>{c.academicYear===data.context.academicYear&&c.term===data.context.term?<button disabled={busy===`restore-${c.id}`} onClick={()=>perform(`restore-${c.id}`,async()=>{const r=await fetchJson('/api/courses/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseSetId:c.id})});if(!r.response.ok)throw new Error(r.data.error||'No previous course version is available.');})} className="min-h-[44px] px-4 rounded-lg border border-line font-semibold">{busy===`restore-${c.id}`?'Restoring…':'Undo last course save'}</button>:<button disabled={busy===`reuse-${c.id}`} onClick={async()=>{const confirmed=window.confirm(`Reuse ${c.title||'this course set'} for the current term? This will replace the current-term course set and keep the previous version available for undo.`);if(!confirmed)return;await perform(`reuse-${c.id}`,async()=>{const r=await fetchJson(`/api/account/course-sets/${c.id}/duplicate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({replaceExisting:true})});if(!r.response.ok)throw new Error(r.data.error||'Could not reuse course set.');})}} className="min-h-[44px] px-4 rounded-lg border border-line font-semibold">{busy===`reuse-${c.id}`?'Reusing…':'Reuse for current term'}</button>}</div>):<div className="p-6 text-center border border-dashed border-line rounded-xl"><BookOpen className="mx-auto w-8 h-8 text-text-muted"/><p className="font-bold mt-2">No saved course sets yet</p><p className="text-sm text-text-secondary mt-1">Build your first course set and it will be remembered here.</p><button onClick={onStartNewTerm} className="mt-4 min-h-[44px] px-4 rounded-lg bg-ink text-white font-semibold">Start a term</button></div>}</div>}
    {tab==='schedules'&&data&&<div className="space-y-3">{data.schedules.length?data.schedules.map((s:any)=><div key={s.id} className="p-4 border border-line rounded-xl"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{s.title||'Saved Schedule'}</p><p className="text-sm text-text-secondary mt-1">{s.term} · {s.academicYear} · {new Date(s.createdAt).toLocaleDateString('en-GB')}</p></div><button title="Mark favorite" onClick={()=>perform(`fav-${s.id}`,async()=>{const r=await fetchJson(`/api/account/schedules/${s.id}/favorite`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({favorite:!Boolean(s.isFavorite)})});if(!r.response.ok)throw new Error(r.data.error||'Could not update favorite.');})} className="min-h-[44px] min-w-[44px] rounded-lg border border-line">{s.isFavorite?<Star className="mx-auto fill-current"/>:<Star className="mx-auto"/>}</button></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>{const title=window.prompt('Schedule name',s.title||'Saved Schedule'); if(title)void perform(`rename-${s.id}`,async()=>{const r=await fetchJson(`/api/account/schedules/${s.id}/rename`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title})});if(!r.response.ok)throw new Error(r.data.error||'Could not rename.');});}} className="min-h-[44px] px-3 border border-line rounded-lg text-sm font-semibold">Rename</button><button onClick={()=>perform(`delete-${s.id}`,async()=>{if(!window.confirm('Delete this saved schedule?')) return;const r=await fetchJson(`/api/account/schedules/${s.id}`,{method:'DELETE'});if(!r.response.ok)throw new Error(r.data.error||'Could not delete.');})} className="min-h-[44px] px-3 border border-red-200 text-red-700 rounded-lg text-sm font-semibold">Delete</button></div></div>):<div className="p-6 text-center border border-dashed border-line rounded-xl"><CalendarDays className="mx-auto w-8 h-8 text-text-muted"/><p className="font-bold mt-2">No saved schedules yet</p><p className="text-sm text-text-secondary mt-1">Generate your first schedule and save it here.</p></div>}</div>}
    {tab==='payments'&&data&&<div className="space-y-5">{pendingPayment&&<div className="p-5 border border-amber-200 bg-amber-50 rounded-2xl"><p className="font-black text-amber-900">Payment under review</p><p className="text-sm text-amber-800 mt-1">Submitted {formatDateTime(pendingPayment.createdAt)} · {pendingPayment.paymentMethod.replace('MANUAL_','')}</p><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="font-bold">✓ Submitted</div><div className="font-bold">● Reviewing</div><div className="text-amber-700">○ Access</div></div></div>}<div className="p-5 border border-line rounded-2xl"><p className="text-xs uppercase text-text-muted">What you have</p><p className="font-black text-xl mt-1">{data.access.accessLabel}</p><p className="text-sm text-text-secondary mt-1">{data.access.expiresOn?`Expires ${formatDate(data.access.expiresOn)}`:'No active paid access'}</p>{data.access.upgradeAvailable&&<button onClick={onOpenUpgrade} className="mt-4 min-h-[44px] px-4 rounded-lg bg-ink text-white font-semibold">Upgrade to Academic Year</button>}</div><div><h3 className="font-bold mb-2">Payment history</h3>{data.payments.length?data.payments.map((x:any)=><div key={x.id} className="p-4 border border-line rounded-xl mb-2"><div className="flex justify-between gap-3"><div><p className="font-semibold">{x.productNameSnapshot || (x.plan==='ACADEMIC_YEAR'?'Academic Year':'Current Term')} · {x.amount} EGP</p><p className="text-xs text-text-muted mt-1">{x.academicYear}{x.term?` · ${x.term}`:''} · {formatDateTime(x.createdAt)} · {x.paymentMethod.replace('MANUAL_','')}</p></div><span className="text-xs font-bold">{x.status}</span></div>{x.rejectionReason&&<p className="mt-2 text-sm text-red-700">Reason: {x.rejectionReason}</p>}<p className="mt-2 text-xs text-text-muted">Receipt ID: {String(x.id).slice(0,8).toUpperCase()}</p></div>):<div className="p-6 border border-dashed border-line rounded-xl text-sm text-text-secondary">No payments yet.</div>}</div><div className="grid sm:grid-cols-2 gap-3">{(data.products||[]).map((p:any)=><div key={p.id} className="p-4 border border-line rounded-xl"><p className="font-bold">{p.name}</p><p className="text-sm text-text-secondary mt-1">{p.amount} {p.currency}</p><p className="text-xs text-text-muted mt-1">One-time access</p></div>)}</div></div>}
    {tab==='notifications'&&<div className="space-y-2">{notifications.length? <>{notifications.map(n=><button key={n.id} onClick={()=>n.readAt?null:perform(`n-${n.id}`,async()=>{const r=await fetchJson(`/api/account/notifications/${n.id}/read`,{method:'POST'});if(!r.response.ok)throw new Error('Could not update notification.');})} className={`w-full text-left p-4 border rounded-xl ${n.readAt?'border-line bg-white':'border-accent/30 bg-accent/5'}`}><div className="flex gap-3"><Bell className="w-4 h-4 mt-1"/><div><p className="font-bold text-sm">{n.title}</p><p className="text-sm text-text-secondary mt-1">{n.message}</p><p className="text-xs text-text-muted mt-2">{formatDateTime(n.createdAt)}</p></div></div></button>)}</>:<div className="p-6 text-center border border-dashed border-line rounded-xl"><p className="font-bold">No notifications</p><p className="text-sm text-text-secondary mt-1">Important account and payment updates will appear here.</p></div>}{notifications.some(n=>!n.readAt)&&<button onClick={()=>perform('readall',async()=>{const r=await fetchJson('/api/account/notifications/read-all',{method:'POST'});if(!r.response.ok)throw new Error('Could not update notifications.');})} className="min-h-[44px] px-4 border border-line rounded-lg font-semibold">Mark all read</button>}</div>}
    {tab==='security'&&data&&<div className="space-y-5">
      <div className="p-4 border border-line rounded-xl flex gap-3"><Shield className="w-5 h-5 mt-1"/><div><p className="font-bold">Account security</p><p className="text-sm text-text-secondary mt-1">Your verified MIU email is the identity for this account. Sensitive changes require your current password.</p><p className="text-sm mt-2 font-semibold">{data.profile.email}</p></div></div>
      <form onSubmit={changePassword} className="p-4 border border-line rounded-xl space-y-3"><div><p className="font-bold">Change password</p><p className="text-sm text-text-secondary mt-1">Changing it signs out other sessions.</p></div><input type="password" minLength={8} required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Current password" className="w-full min-h-[44px] border border-line rounded-lg px-3"/><input type="password" minLength={8} maxLength={128} required value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="New password" className="w-full min-h-[44px] border border-line rounded-lg px-3"/><input type="password" minLength={8} maxLength={128} required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Confirm new password" className="w-full min-h-[44px] border border-line rounded-lg px-3"/><button disabled={busy==='password'} className="min-h-[44px] px-4 rounded-lg bg-ink text-white font-semibold">{busy==='password'?'Changing…':'Change password'}</button></form>
      <form onSubmit={changeEmail} className="p-4 border border-line rounded-xl space-y-3"><div><p className="font-bold">Change MIU email</p><p className="text-sm text-text-secondary mt-1">The new MIU address must be verified before it replaces your current email.</p></div><input type="email" required value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="newstudent@miuegypt.edu.eg" className="w-full min-h-[44px] border border-line rounded-lg px-3"/><input type="password" minLength={8} required value={emailPassword} onChange={e=>setEmailPassword(e.target.value)} placeholder="Current password" className="w-full min-h-[44px] border border-line rounded-lg px-3"/><button disabled={busy==='email'} className="min-h-[44px] px-4 rounded-lg border border-line font-semibold">{busy==='email'?'Sending…':'Start email change'}</button></form>
      <div className="grid sm:grid-cols-2 gap-3"><button onClick={async()=>perform('other-sessions',async()=>{const r=await fetchJson('/api/auth/revoke-other-sessions',{method:'POST'});if(!r.response.ok)throw new Error(r.data.error||'Could not sign out other sessions.');})} className="min-h-[48px] border border-line rounded-xl font-semibold">Sign out other sessions</button><button onClick={async()=>{if(!window.confirm('Sign out every Gadwal session? You will need to sign in again.'))return;await perform('all-sessions',async()=>{const r=await fetchJson('/api/auth/revoke-all-sessions',{method:'POST'});if(!r.response.ok)throw new Error(r.data.error||'Could not sign out all sessions.');onLogout?.();});}} className="min-h-[48px] border border-line rounded-xl font-semibold">Sign out all sessions</button></div>
      <div className="grid sm:grid-cols-2 gap-3"><button onClick={()=>{window.location.href='/api/account/export';}} className="min-h-[48px] border border-line rounded-xl font-semibold flex items-center justify-center gap-2"><Download className="w-4 h-4"/>Export my data</button><button disabled={Boolean(data.profile.deletionScheduledFor)||busy==='delete'} onClick={deleteAccount} className="min-h-[48px] border border-red-200 text-red-700 rounded-xl font-semibold flex items-center justify-center gap-2"><Trash2 className="w-4 h-4"/>{busy==='delete'?'Scheduling…':'Delete account'}</button></div>
      <div className="text-xs text-text-muted">Account deletion has a 7-day grace period so accidental requests can be cancelled. After the grace period, your Gadwal data is erased and this account identity can no longer access Gadwal. Password reset is also available through the signed-out recovery flow.</div>
      <button onClick={()=>onOpenAuth?.('forgot')} className="min-h-[46px] border border-line rounded-xl font-semibold w-full">Forgot or reset password</button>
    </div>}
    {tab==='help'&&<div className="space-y-4"><div className="p-4 border border-line rounded-xl"><p className="font-bold">How OCR works</p><p className="text-sm text-text-secondary mt-1">Gadwal reads your uploaded timetable screenshots and shows the extracted courses for you to review before generating schedules.</p></div><div className="p-4 border border-line rounded-xl"><p className="font-bold">Free run</p><p className="text-sm text-text-secondary mt-1">Each verified MIU student gets one complete successful schedule-generation run. Failed attempts do not consume it.</p></div><div className="p-4 border border-line rounded-xl"><p className="font-bold">Payments</p><p className="text-sm text-text-secondary mt-1">Manual payment submissions remain pending until an admin verifies the transfer and activates your entitlement.</p></div><div className="p-4 border border-line rounded-xl"><p className="font-bold">Need help?</p><p className="text-sm text-text-secondary mt-1">Contact Gadwal support with your MIU email and a clear description of the problem.</p>{feedbackEmail&&<a href={`mailto:${feedbackEmail}`} className="inline-flex min-h-[44px] items-center mt-3 px-4 rounded-lg bg-ink text-white font-semibold">Contact support</a>}</div></div>}
  </ModalShell>;
};
